<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org main article template
 *
 * This template does not output anything but selects a specific partial output
 * for a class (or a default partial)
 */

// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
);

$this->renderx(array(
    'description' => $this->description
));

/*
if (isset($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'])) {
    $types = array();
    foreach ($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'] as $property) {
        if ((isset($property['value'])) && (Erfurt_Uri::check($property['value']))) {
            $types[$property['value']] = true;
        }
    }

    switch (true) {
        case (isset($types['http://xmlns.com/foaf/0.1/Project'])):
            echo $this->partial('aksw2011/types/project.phtml', $templateData);
            break;
        case (isset($types['http://xmlns.com/foaf/0.1/Group'])):
            echo $this->partial('aksw2011/types/group.phtml', $templateData);
            break;
        case (isset($types['http://xmlns.com/foaf/0.1/Document'])):
            echo $this->partial('aksw2011/types/document.phtml', $templateData);
            break;
        case (isset($types['http://xmlns.com/foaf/0.1/Person'])):
            echo $this->partial('aksw2011/types/person.phtml', $templateData);
            break;
        default:
            // no specific template found
            echo $this->partial( 'aksw2011/types/document.phtml', $templateData);
            break;
    }
}
 */
