<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * querylist abstract element template (site independent)
 *
 * this template is used in combination with the querylist helper to render
 * lists of resources which match a given SPARQL query
 * mentioned options:
 * - heading (default: h2)
 *
 * TODO: make more independend from the query (e.g. take the first)
 * TODO: include depiction / logo
 */

// prepare vars from the querylist helper
$resourceUri = $this->resourceUri;
$title       = $this->title;
$oddclass    = $this->oddclass;
$heading     = (isset($this->heading)) ? $this->heading : 'h2';

if ($this->listhint == 'first') {
    echo "<div class='query-list-abstract'>" . PHP_EOL;
}

// if we have a literal item, do not do anything but a html comment
if (!Erfurt_Uri::check($resourceUri)) {
    echo "<!-- $title is not a resource -->";
} else {
    // prepare the abstract
    $moreLink = $this->link(array('uri' => $resourceUri, 'text' => '[read more]'));
    $abstract = $this->literal(array(
        'uri' => $resourceUri,
        'property' => 'dcterms:abstract',
        'tag' => 'p', 'class' => 'abstract',
        'isuffix' => ' ' . $moreLink)
    );
    $headingLink = $this->link(array(
        'uri' => $resourceUri, 'text' => $title,
        'prefix' => "<$heading>", 'suffix' => "</$heading>"
    ));
?>
    <div about="<?php echo $this->curie($resourceUri) ?>">
    <?php echo $headingLink ?>
    <?php echo $abstract ?>
    </div>
<?php
}

if ($this->listhint == 'last') {
    echo "</div>" . PHP_EOL;
}
