<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * querylist abstract element template (site independent)
 *
 * this template is used in combination with the querylist helper to render
 * lists of resources which match a given SPARQL query
 * mentioned options:
 * - heading (default: h2)
 *
 * TODO: make more independend from the query (e.g. take the first)
 * TODO: include depiction / logo
 */

// prepare vars from the querylist helper
$resourceUri = $this->resourceUri;
$title       = $this->title;
$oddclass    = $this->oddclass;
$heading     = (isset($this->heading)) ? $this->heading : 'h2';

if ( ($this->listhint == 'first') || ($this->rowcount == 1) ) {
    echo "<div class='query-list-abstract'>" . PHP_EOL;
}

// if we have a literal item, do not do anything but a html comment
if (!Erfurt_Uri::check($resourceUri)) {
    echo "<!-- $title is not a resource -->";
} else {
    // prepare the heading
    $headingLink = $this->link(array(
        'uri'    => $resourceUri, 'text' => $title,
        'prefix' => "<$heading>", 'suffix' => "</$heading>"
    ));

    // prepare the logo link
    $logo          = $this->img(array(
        'property' => 'foaf:logo',
        'class'    => 'logo',
        'alt'      => 'logo',
        'prefix'   => '<div class="logo">',
        'suffix'   => '</div>'
    ));
    if ($logo != '') {
        $logolink = $this->link(array(
            'uri'    => $resourceUri, 'text' => $logo,
            'prefix'   => '<!-- project logo start -->',
            'suffix'   => '<!-- project logo end -->',
        ));
    } else {
        $logolink = '';
    }

    // prepare the abstract
    $moreLink      = $this->link(array('uri' => $resourceUri, 'text' => 'Read more about '.$title));
    $abstract      = $this->literal(array(
        'uri'      => $resourceUri,
        'property' => 'dcterms:abstract',
        'tag'      => 'p',
        'class'    => 'abstract',
        'isuffix'  => ' ' . $moreLink)
    );
?>
    <div about="<?php echo $this->curie($resourceUri) ?>" class="abstract <?php echo $logolink?'abstract-with-logo':''; ?>">
    <?php echo $headingLink ?>
    <?php echo $logolink ?>
    <?php echo $abstract ?>
    </div>
<?php
}

if ( ($this->listhint == 'last') || ($this->rowcount == 1) ) {
    echo "</div>" . PHP_EOL;
}
