<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * querylist li element template (site independent)
 *
 * this template is used in combination with the querylist helper to render
 * lists of resources which match a given SPARQL query
 *
 * TODO: make more independend from the query (e.g. take the first)
 */

// prepare vars from the querylist helper
$resourceUri = $this->resourceUri;
$title       = $this->title;
$oddclass    = $this->oddclass;
$tag         = (isset($this->tag)) ? $this->tag : 'ul';

if ($this->listhint == 'first') {
    echo "<$tag>" . PHP_EOL;
}

// if we have a literal item, do not do anything but an li item
if (!Erfurt_Uri::check($resourceUri)) {
    echo "<li class='$oddclass'>$title</li>";
} else {
    // prepare resource description
    $resource    = new OntoWiki_Resource($resourceUri, OntoWiki::getInstance()->selectedModel);
    $description = $resource->getDescription();
    $description = $description[$resourceUri];

    // prepare the link url
    $url = $resourceUri;
    //$url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
    //$url->setParam('r', $resourceUri, true);

    // prepare the optional hookline
    $hookline = $this->literalTag(
        $description,
        'http://aksw.org/schema/hookline',
        array('tag' => 'span', 'class' => 'hookline', 'prefix' => ' – ')
    );
?>
    <li class="<?php echo $oddclass ?>" about="<?php echo $url ?>">
        <a href="<?php echo $url ?>">
            <span property="rdfs:label"><?php echo $title ?></span>
        </a><?php echo $hookline ?>
    </li>
<?php
}

if ($this->listhint == 'last') {
    echo "</$tag>" . PHP_EOL;
}
