<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org footer template
 */
$editUrl = $this->wikiBaseUrl .'view?r=' . urlencode($this->resourceUri);
?>
<footer id="footer">
    <aside id="articleinfo">
        <div class="subc">
            <?php echo $this->partial('aksw2011/lastchange.phtml', $this->lastchange($this->resourceUri)); ?>
            Functions:
            <ul>
                <li>download resource as
                    <a rel="nofollow" href="<?php echo $this->resourceUri ?>.rdf">rdf/xml</a> or
                    <a rel="nofollow" href="<?php echo $this->resourceUri ?>.tt">n3</a>
                </li>
                <li><a rel="nofollow" href="<?php echo $editUrl ?>">view / edit resource</a></li>
                <li><a rel="nofollow" href="">view / edit template</a></li>
            </ul>
        </div>
    </aside>
    <aside id="userinfo">
        <div class="subc">
        </div>
    </aside>
</footer>
