<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org footer template
 */
$editUrl = $this->wikiBaseUrl .'view?r=' . urlencode($this->resourceUri);
?>
<footer id="footer">
    <aside id="articleinfo">
        <div class="subc">
            <?php echo $this->partial('local/lastchange.phtml', $this->lastchange($this->resourceUri)); ?>

            <dl class="resourceoptions">
                <dt class="hideme">Resource info &amp; options</dt>
                <dd>
                    <span class="icon icon-resource-download" title="download resource as">download resource as:</span>
                    <a rel="nofollow" href="<?php echo $this->resourceUri ?>.rdf">rdf/xml</a>,
                    <a rel="nofollow" href="<?php echo $this->resourceUri ?>.ttl">turtle</a>
                </dd>
                <dd><span class="icon icon-resource-edit"></span> <a rel="nofollow" href="<?php echo $editUrl ?>">view/edit resource</a></dd>
                <dd><span class="icon icon-template-edit"></span> <a rel="nofollow" href="https://github.com/AKSW/aksw.org/tree/master/site/types">view/edit templates</a></dd>
                <!-- dd>
                    <span class="icon icon-browse" title="browse resource using">browse resource using:</span>
                    <a rel="nofollow" href="http://dataviewer.zitgist.com/?uri=<?php echo urlencode($this->resourceUri); ?>">Zitgist</a>,
                    <a rel="nofollow" href="http://dig.csail.mit.edu/2005/ajar/release/tabulator/0.8/tab.html?uri=<?php echo urlencode($this->resourceUri); ?>">Tabulator</a>
                </dd-->
            </dl>
        </div>
    </aside>
    <aside id="userinfo">
        <div class="subc">
            <dl class="siteoptions">
                <dt class="hideme">aksw.org site options</dt>
                <dd>
                    <span class="icon icon-service-github">Github:</span>
                    <a rel="nofollow" href="https://github.com/AKSW/aksw.org">site repository</a>
                </dd>
                <dd>
                    <span class="icon icon-service-github">Github:</span>
                    <a rel="nofollow" href="https://github.com/AKSW/aksw.org/issues">site issues</a>
                </dd>
                <dd>
                    <span class="icon icon-service-xxx">Service:</span>
                    <a rel="nofollow" href="https://github.com/AKSW/aksw.org/wiki/_pages">site documentation</a>
                </dd>
            </dl>
        </div>
    </aside>
</footer>
<script type="text/javascript">
  var GoSquared = {};
  GoSquared.acct = "GSN-386459-F";
    (function(w){
        function gs(){
              w._gstc_lt = +new Date;
              var d = document, g = d.createElement("script");
              g.type = "text/javascript";
              g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
              var s = d.getElementsByTagName("script")[0];
              s.parentNode.insertBefore(g, s);
            }
        w.addEventListener ?
          w.addEventListener("load", gs, false) :
          w.attachEvent("onload", gs);
      })(window);
  </script>
