<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2013, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org header template
 */
?>
<header id="header">
    <h1><a href="/"><img src="<?php echo $this->baseUri; ?>/images/logo-aksw.png" alt="Agile Knowledge Engineering and Semantic Web (AKSW) Research Group" /></a></h1>
<?php
$navOptions = array(
    'navResource' => 'http://aksw.org/Navigation/Main',
    'navId' => 'nav-main',
    'suffix'    => '<!-- /#nav-main -->',
    'activeUrl' => $this->resourceUri
);
echo $this->navigationList($navOptions);
?>
<?php
$navOptions = array(
    'navResource' => 'http://aksw.org/Navigation/Top',
    'navId' => 'nav-top',
    'suffix'    => '<!-- /#nav-top -->',
    'activeUrl' => $this->resourceUri
);
echo $this->navigationList($navOptions);
?>
    <nav>
        <form id="search" action="#" method="get" role="search">
            <fieldset>
                <legend>Search</legend>
                <input type="text" id="searchterm" type="text" value="" />
                <button type="sumbit">Search</button>
            </fieldset>
        </form>
    </nav>
    <aside id="associations">
        <h2>Hosted by</h2>
        <a href="http://www.uni-leipzig.de"><img src="<?php echo $this->baseUri; ?>/images/logo-unileipzig.png" alt="Universität Leipzig" /></a> <span>,</span>
        <a href="http://infai.org"><img src="<?php echo $this->baseUri; ?>/images/logo-infai.png" alt="InfAI: Institut für Angewandte Informatik" /></a>
        <h2>Funded by</h2>
        <div class="small">
            <a href="http://www.bmbf.de/en/"><img src="<?php echo $this->baseUri; ?>/images/logo-bmbf.png" alt="Federal Ministry of Education" /></a> <span>,</span>
            <a href="http://cordis.europa.eu/fp7/home_en.html"><img src="<?php echo $this->baseUri; ?>/images/logo-fp7.png" alt="EU Seventh Framework Programme (FP7)" /></a> <span>,</span>
            <a href="http://www.daad.de/en/" class="small"><img src="<?php echo $this->baseUri; ?>/images/logo-daad.png" alt="German Academic Exchange Service" /></a> <span>,</span>
            <a href="http://www.dfg.de/en/" class="small"><img src="<?php echo $this->baseUri; ?>/images/logo-dfg.png" alt="German Research Foundation" /></a>
        </div>
    </aside> <!-- /#associations -->
</header> <!-- /#header -->
<hr class="hideme" />

