<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2013, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org layout template
 *
 * the most out template layer
 */

// edit link for the universal edit button
$editUrl = $this->wikiBaseUrl .'view?r=' . urlencode($this->resourceUri);

// this is the standard template data
$templateData = $this->templateData;

$memoryModel = new Erfurt_Rdf_MemoryModel($this->description);
$types = $memoryModel->getValues($this->resourceUri, EF_RDF_TYPE);

?><!doctype html>
<html lang="en" prefix="dc:http://purl.org/dc/terms/ foaf:http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?php echo $this->pingbackUrl ?>" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script type="text/javascript">document.documentElement.className += 'js';</script>
    <!--[if lte IE 8]>
        <script type="text/javascript">
            var html4elements = 'article footer header nav section aside time';
            html4elements.replace(/\w+/g,function(n){document.createElement(n)})
        </script>
    <![endif]-->

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />

    <link
        rel="stylesheet" type="text/css" media="all"
        href="<?php echo $this->baseUri ?>/css/all.min.css"
        title="Standard" />
    <link
        rel="stylesheet" type="text/css" media="all"
        href="<?php echo $this->baseUri ?>/css/addons.css"
        title="Standard" />
    <link
        rel="icon" 
        type="image/png" 
        href="<?php echo $this->baseUri ?>/images/favicon.png" />

    <link rel="alternate"
        type="application/wiki" 
        title="Edit this page!" 
        href="javascript:myEdit()" />

    <!-- TODO: we should include all the js via a parallel loading script.
         * separates the js logic from templates/html/caches
         * improves performance
    -->
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUri ?>/libs/rscarousel/jquery.rs.carousel.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/libs/rscarousel/jquery.rs.carousel-autoscroll.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUri ?>/libs/fancybox/jquery.fancybox-1.3.4.css"/>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/libs/fancybox/jquery.fancybox-1.3.4.pack.js"></script>

    <script type="text/javascript">RDFAUTHOR_BASE='<?php echo $this->libraryUrlBase ?>RDFauthor';</script>
    <script type="text/javascript" src="<?php echo $this->libraryUrlBase ?>RDFauthor/src/rdfauthor.js"></script>
    <script type="text/javascript">
        function myEdit() {
            RDFauthor.edit({
                loadOwStylesheet: false,
                onSubmitSuccess: function() { 
                  // HACK: reload whole page after 500 ms
                  window.setTimeout(function () {
                      window.location.href = window.location.href;
                  }, 500);
                },
                targetSparqlEndpoint: '/sparql',
                targetUpdateEndpoint: '/update',
                targetGraph: 'http://aksw.org/',
                targetResource: '<?php echo $this->resourceUri ?>'
            });
        };
    </script>

    <script type="text/javascript" src="<?php echo $this->baseUri ?>/scripts/settings/media.dev.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/scripts/search.js"></script>

    <title><?php echo $templateData['title'] ?> &mdash; <?php echo $this->siteConfig['name'] ?></title>

<?php
    // includes the GA header script
    $this->headScriptGoogleAnalytics('UA-241023-8');
    // includes the exhibit header links
    $this->headScriptExhibit( array(
        array ('uri' => 'http://aksw.org/schema/publicationTag',
               'sprintf' => 'http://aksw.org/BibsonomyProxy/exhibit-proxy.php?suffix=user/aksw/%s&callback=cb'),
        array ('uri' => 'http://lod2.eu/schema/exhibitData')
    ));
    // other head scripts
    $this->headScript();
?>
</head>
<body
    prefix="<?php foreach ($this->namespaces as $prefix => $ns): echo $prefix . ':' . $ns . ' '; endforeach; ?>"
    about="<?php echo $this->resourceUri ?>"
    typeof="<?php foreach ($types as $type) {echo $type['value'] . ' '; } ?>"
    >
    <div class="page_margins">
        <div id="page">
                <?php echo $this->partial('local/header.phtml', $templateData) ?>
            <article id="content">
                <?php //echo $this->partial('local/breadcrumbs.phtml', $templateData) ?>
                <?php echo $this->renderx(); ?>
            </article> <!-- /#content -->
            <section id="sidecontent">
                <?php echo $this->partial('local/side.phtml', $templateData) ?>
            </section> <!-- /#sidecontent -->
            <?php echo $this->partial('local/footer.phtml', $templateData) ?>
        </div> <!-- /#page -->
    </div> <!-- /.page_margins -->
</body>
</html>

