<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org feed template
 *
 * arranges the news feed for the resource
 */


// prepare module options
$moduleOptions = array(
    'noChrome' => true,
    'template' => 'local/items/feedentry',
    'fallbackFeed' => 'http://blog.aksw.org/feed/'
);
$moduleConfig = new Zend_Config($moduleOptions);
$content = trim($this->module('feeds', $moduleConfig));
?>

    <aside id="associations">
        <h2>Hosted by</h2>
        <a href="http://www.uni-leipzig.de"><img src="<?php echo $this->baseUri; ?>/images/logo-unileipzig.png" alt="Universität Leipzig" /></a> <span>,</span>
        <a href="http://infai.org"><img src="<?php echo $this->baseUri; ?>/images/logo-infai.png" alt="InfAI: Institut für Angewandte Informatik" /></a>
        <h2>Funded by</h2>
        <div class="small">
            <a href="http://www.bmbf.de/en/"><img src="<?php echo $this->baseUri; ?>/images/logo-bmbf.png" alt="Federal Ministry of Education" /></a> 
<span>,</span>
            <a href="http://cordis.europa.eu/fp7/home_en.html"><img src="<?php echo $this->baseUri; ?>/images/logo-fp7.png" alt="EU Seventh Framework Programme (FP7)" /></a> <span>,</span>
            <a href="http://www.daad.de/en/" class="small"><img src="<?php echo $this->baseUri; ?>/images/logo-daad.png" alt="German Academic Exchange Service" /></a> 
<span>,</span>
            <a href="http://www.dfg.de/en/" class="small"><img src="<?php echo $this->baseUri; ?>/images/logo-dfg.png" alt="German Research Foundation" /></a>
<span>,</span>
            <a href="http://www.bmwi.de/DE/root.html"><img src="<?php echo $this->baseUri; ?>/images/logo-bmwi.png" alt="Ministry for Economic Affairs and Energy" /></a>
<span>,</span>
            <a href="https://ec.europa.eu/programmes/horizon2020/"><img src="<?php echo $this->baseUri; ?>/images/logo-horizon2020.png" alt="Horizon2020" /></a>
<span>,</span>
            <a href="http://www.eurostars.dlr.de/de/1315.php"><img src="<?php echo $this->baseUri; ?>/images/logo-eurostars.png" alt="Eurostars" /></a>
        </div>
    </aside> <!-- /#associations -->
<?php if (!empty($content)): ?>
<h1>News</h1>
<?php echo $content; ?>
<?php endif; ?>
