<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org project template
 *
 * arranges the content for the project class
 */

?>
<?php if (($abstract = $this->literal(array('property' => 'dcterms:abstract', 'tag' => 'p', 'class' => 'abstract'))) |
          ($title = $this->title)
         ): ?>
<header class="intro">
<?php

    if ($title)
    {
        echo '<h1>'.$title.'</h1>'.PHP_EOL;
    }

    echo $abstract?$abstract.PHP_EOL:'';

?>
</header> <!-- /.intro -->
<?php endif; ?>

<?php
echo $this->literal(array('tag' => 'div', 'class' => 'content')); // uses default content properties
