<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org project template
 *
 * arranges the content for the project class
 */

// prepare hookline and abstract (both optional)
// yes, hookline also for documents please :-)
$hookline = $this->literal(array(
    'property' => 'aksw:hookline',
    'class' => 'hookline',
    'prefix' => '<span class="hideme">:</span> '
));
$abstract = $this->literal(array(
    'property' => 'dcterms:abstract',
    'tag' => 'p',
    'class' => 'abstract'
));

?>
<header class="intro">
    <h1><?php echo $this->title . $hookline ?></h1>
    <?php echo $abstract ?>
</header> <!-- /.intro -->
<?php
echo $this->literal(array('tag' => 'div', 'class' => 'content')); // uses default content properties
?>

<!-- REMOVE THIS AFTER PROPER BIBSONOMY INTEGRATION -->

<nav class="nav-sidelinks">
    <div class="exhibit-filter-tools">
        <!-- use this for lists containing only a few publications and authors -->
        <div ex:facetClass="Cloud" ex:role="facet" ex:showMissing="false" ex:expression=".year" ex:facetLabel="Year" ex:sortDirection="reverse"></div>
        <div ex:facetClass="Cloud" ex:role="facet" ex:showMissing="false" ex:expression=".pub-type" ex:facetLabel="Type" ex:sortMode="count"></div>
        <div ex:facetClass="Cloud" ex:role="facet" ex:showMissing="false" ex:expression=".author" ex:facetLabel="(Co-)Authors" ex:sortMode="count"></div>
    </div>
</nav>

<div class="exhibit-filter-tools">
    <!-- use this for lists cantaining a lot of publication and authors-->
    <h2 class="hideme">Filters</h2>
    <div ex:role="facet" ex:facetClass="TextSearch" ex:facetLabel="Keyword"></div>
    <div class="subcolumns equalize">
        <div class="c33l"><div class="subcl">
            <div ex:role="facet" ex:showMissing="false" ex:expression=".year" ex:facetLabel="Year" ex:sortDirection="reverse" ex:height="15em"></div>
        </div></div>
        <div class="c33l"><div class="subc">
            <div ex:role="facet" ex:showMissing="false" ex:expression=".pub-type" ex:facetLabel="Type" ex:sortMode="count" ex:height="15em"></div>
        </div></div>
        <div class="c33r"><div class="subcr">
            <div ex:role="facet" ex:showMissing="false" ex:expression=".author" ex:facetLabel="(Co-)Authors" ex:sortMode="count" ex:height="15em"></div>
        </div></div>
    </div>
</div> <!-- /.exhibit-filter-tools -->

<div ex:role="view" ex:grouped="false" ex:orders=".year,.label" ex:directions="descending,ascending" ex:showSummary="true" ex:showDuplicates="false">

    <div ex:role="lens" ex:itemTypes="Publication" style="display: none">
        <strong>
            <span ex:content="if(exists(.url), concat('<a href=', .url, '>', .label, '</a>'), .label)"></span>
            <span ex:if-exists=".author">
                <span class="meta"><em>by</em> <span class="author" ex:content=".author"></span></span>
            </span>
        </strong>
        <span class="meta">
            <span ex:content="if(exists(.booktitle), concat('<em>in</em> ', .booktitle), '')"></span>
            <span class="journal" ex:content="if(exists(.journal), concat('<em>in</em> ', .journal), '')"></span>
            <span ex:if-exists=".editor">(Editors: <span class="editor" ex:content=".editor"></span>)</span>
            <a ex:if-exists=".biburl" ex:href-content=".biburl" >[BibTex<span class="hideme"> of <span ex:content=".label"></span></span>]</a>
        </span>
        <span class="note" ex:content="if(exists(.note), concat('<br/><em>Note:</em> ', .note), '')"></span>
        <span class="abstract" ex:content="if(exists(.abstract), concat('<br/><em>Abstract:</em> ', .abstract), '')"></span>
        
    </div>

</div>
