<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org group template
 *
 * arranges the content for the group class
 */

// prepare hookline and abstract (both optional)
// yes, hookline also for groups please :-)
$hookline = $this->literal(array(
    'property' => 'aksw:hookline',
    'class' => 'hookline',
    'prefix' => '<span class="hideme">:</span> '
));
$abstract = $this->literal(array(
    'property' => 'dcterms:abstract',
    'tag' => 'p',
    'class' => 'abstract'
));

?>
<header class="intro">
    <h1><?php echo $this->title . $hookline ?></h1>
    <?php echo $abstract ?>
</header> <!-- /.intro -->
<?php
echo $this->literal(array('tag' => 'div', 'class' => 'content')); // uses default content properties
?>
<div class="subcolumns">
<?php // RESEARCH AREAS
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX aksw: <http://aksw.org/schema/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> aksw:researchAreas ?resourceUri.
}
';
if ($areas = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <div class="c50l">
        <div class="subc">
            <h1>Research Areas</h1>
            <?php echo $areas ?>
        </div>
    </div>
<?php endif; ?>
<?php // MEMBER
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> foaf:member ?resourceUri.
?resourceUri a foaf:Person.
?resourceUri foaf:name ?name.
}
';
if ($member = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <div class="c50r">
        <div class="subc">
            <h1>Member</h1>
            <?php echo $member ?>
        </div>
    </div>
<?php endif; ?>
</div>

<?php // PROJECTS
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> foaf:member ?person.
?person foaf:currentProject ?resourceUri.
?resourceUri a foaf:Project.
}
';
if ($projects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <h1>Projects</h1>
    <?php echo $projects ?>
<?php endif; ?>
