<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org project template
 *
 * arranges the content for the project class
 */

// TODO: move to config?
$depiction = 'http://xmlns.com/foaf/0.1/depiction';

// add an depiction if one exist
// TODO: look for foaf:img (and maybe others) too and use the most specific one
// TODO: use instant picture creator with URI mode here
$imgRel = null; $imgSrc = null; $imgAlt = null; $imgClass = null;
if (isset($this->description[$depiction])) {
    $imgRel   = $this->curie($depiction);
    $imgSrc   = $this->description[$depiction][0]['value'];
    $imgAlt   = 'Depiction of ' . htmlentities($this->title);
    $imgClass = 'depiction';
    // echo "<img rel='$imgRel' src='$imgSrc' alt='$imgAlt' class='$imgClass' />";
}

?>
<h1><?php
    echo $this->title;
    echo $this->literal(array(
        'property' => 'aksw:hookline', 'class' => 'hookline',
        'prefix' => '<span class="hideme">:</span> '
        ));
?></h1>


<?php if (($abstract = $this->literal(array('property' => 'dcterms:abstract', 'tag' => 'p', 'class' => 'abstract'))) ||
          (isset($buttons) && is_array($buttons) && count($buttons) > 0) ||
          (isset($screenshots) && is_array($screenshots) && count($screenshots) > 0) ||
          (isset($contacts) && is_array($contacts))): ?>
<header class="intro">
<?php

    if (isset($screenshots) && is_array($screenshots))
    {
        echo '<div class="widget_depictions">'.PHP_EOL;
        // TODO: insert first pic big and thumbs for all, javascriptify this lates to enable switching between pics
        echo '<div class="widget_depictions_big"><img rel="'.$screenshots[0]['rel'].'" alt="'.$screenshots[0]['label'].'" src="'.$screenshots[0]['uri'].'" class="depiction" /></div>'.PHP_EOL;
        echo '</div>'.PHP_EOL;
    }

    echo $abstract?$abstract.PHP_EOL:'';

    if (isset($buttons) && is_array($buttons))
    {
        echo '<p class="button-row">'.PHP_EOL;
        foreach ($buttons as $button)
        {
            echo '<a class="button" href="'.$button['uri'].'">'.htmlentities($button['label']).'</a>'.PHP_EOL;
        }
        echo '</p>'.PHP_EOL;
    }
?>
</header> <!-- /.intro -->
<?php endif; ?>

<?php
echo $this->literal(array('tag' => 'div', 'class' => 'content')); // uses default content properties

?>
<div class="subcolumns">
<?php // RESEARCH AREAS
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX aksw: <http://aksw.org/schema/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> aksw:researchAreas ?resourceUri.
}
';
if ($areas = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <div class="c50r">
        <div class="subc">
            <h1>Research Areas</h1>
            <ul>
            <?php echo $areas ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<?php // MEMBER
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> foaf:member ?resourceUri.
?resourceUri a foaf:Person.
?resourceUri foaf:name ?name.
}
';
if ($member = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <div class="c50r">
        <div class="subc">
            <h1>Member</h1>
            <ul>
            <?php echo $member ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
</div>

<?php // PROJECTS
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> foaf:member ?person.
?person ?relation ?resourceUri.
?resourceUri a foaf:Project.
}
';
if ($projects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <h1>Projects</h1>
    <ul>
    <?php echo $projects ?>
    </ul>
<?php endif; ?>
