<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org project template
 *
 * arranges the content for the project class
 */

// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper,
                'options'           => $this->options
            );
?>
<h1><?php echo $this->title ?></h1>
<header class="intro">
<?php echo $this->returnLiteralTag($this->description,
    'http://aksw.org/schema/abstract', array('tag' => 'p', 'class' => 'abstract'));
?>
</header> <!-- /.intro -->
<?php echo $this->returnLiteralTag($this->description,
    'http://aksw.org/schema/content', array('tag' => 'p', 'class' => 'abstract'));
?>
<div class="subcolumns">
<?php // RESEARCH AREAS
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX aksw: <http://aksw.org/schema/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> aksw:researchAreas ?resourceUri.
}
';
if ($areas = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <div class="c50r">
        <div class="subc">
            <h2>Research Areas</h2>
            <ul>
            <?php echo $areas ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<?php // MEMBER
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> foaf:member ?resourceUri.
?resourceUri a foaf:Person.
?resourceUri foaf:name ?name.
}
';
if ($member = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <div class="c50r">
        <div class="subc">
            <h2>Member</h2>
            <ul>
            <?php echo $member ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
</div>

<?php // PROJECTS
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> foaf:member ?person.
?person ?relation ?resourceUri.
?resourceUri a foaf:Project.
}
';
if ($projects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
    <h2>Projects</h2>
    <ul>
    <?php echo $projects ?>
    </ul>
<?php endif; ?>
