<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org project template
 *
 * arranges the content for the project class
 */

// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper,
                'options'           => $this->options
            );
?>

<h1><?php echo $this->title ?></h1>
<header class="intro">
<?php echo $this->literalTag($this->description,
    'http://purl.org/dc/terms/abstract', array('tag' => 'p', 'class' => 'abstract'));
?>
</header> <!-- /.intro -->
<?php echo $this->literalTag($this->description,
    'http://aksw.org/schema/content', array('tag' => 'p', 'class' => 'abstract'));
?>
<?php
// raw content is added in addition to sioc or formatted content
$rawContent = 'http://lod2.eu/schema/contentRaw';
if (isset($this->description[$rawContent])) {
    echo '<div property="' . $this->curie($rawContent) . '">' . PHP_EOL;
    echo $this->description[$rawContent][0]['value'];
    echo '</div>';
}
?>
