<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org (foaf:)Person template
 *
 * this template renders a person
 */

// TODO: all data available

$name = 'name'; $depictions = array(true); $contacts = array(true);

?>
<?php if ($name |
          (is_array($depictions) && count($depictions) > 0) |
          (is_array($contacts))
         ): ?>
<header class="intro foaf_Person">
<?php
    if ($title = $this->title)
    {
        echo '<h1 class="hideme">'.$title.'</h1>'.PHP_EOL;
    }
    
    echo $this->renderx(array('template'=>'aksw2011/items/vcardperson.phtml'));
?>
</header> <!-- /.intro -->
<?php endif; ?>

<?php
echo $this->literal(array('tag' => 'div', 'class' => 'content')); // uses default content properties

?>
<?php // Current Projects
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
    <'.$this->resourceUri.'> foaf:currentProject ?resourceUri.
}
';
if ($currentProjects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
<h1>Current Projects</h1>
<?php echo $currentProjects ?>
<?php endif; ?>
<?php // Past Projects
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
    <'.$this->resourceUri.'> foaf:pastProject ?resourceUri.
}
';
if ($pastProjects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
<h1>Past Projects</h1>
<?php echo $pastProjects ?>
<?php endif; ?>
