<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org (foaf:)Person template
 *
 * this template renders a person
 */

// TODO: contact information
$contacts = array(
    'Address' => array(
        array(
            'type'=>'Office',
            'label'=>'Johannisgasse 26, Room 5-08, 04103 Leipzig'
        )
    ),
    'Email' => array(
        array(
            'type'=>'Office',
            'label'=>'vorname.nachname@informatik.uni-leipzig.de',
            'url'=>'mailto:vorname.nachname@informatik.uni-leipzig.de'
        )
    ),
    'Phone' => array(
        array(
            'type'=>'Office',
            'label'=>'+49 341 97-32###',
            'url' => 'tel://+493419732###'
        )
    ),
    'Link' => array(
        array(
            'type'=>'Workpage',
            'label'=>'Workpage @ AKSW',
            'url' => '#'
        ),
        array(
            'type'=>'Weblog',
            'label'=>'Personal Techblog',
            'url' => '#'
        )
    )
);

echo $this->renderx( array('template' => 'aksw2011/content.phtml'));

?>
<?php // Current Projects
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
    <'.$this->resourceUri.'> foaf:currentProject ?resourceUri.
}
';
if ($currentProjects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
<h1>Current Projects</h1>
<?php echo $currentProjects ?>
<?php endif; ?>
<?php // Past Projects
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
    <'.$this->resourceUri.'> foaf:pastProject ?resourceUri.
}
';
if ($pastProjects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
<h1>Past Projects</h1>
<?php echo $pastProjects ?>
<?php endif; ?>

