<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org project template
 *
 * arranges the content for the project class
 */

// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper,
                'options'           => $this->options
            );
?>

<h1><?php echo $this->title ?></h1>
<nav class="nav-sidelinks">
    <ul>
        <li><a href="#">SoftWiki</a></li>
        <li><a href="#">OntoWiki</a></li>
        <li><a href="#">DBpedia</a></li>
        <li><a href="#">LinkedGeoData</a></li>
        <li><a href="#">Triplify</a></li>
        <li><a href="#">DL-Learner</a></li>
    </ul>
</nav>
<header class="intro">
<?php echo $this->literalTag($this->description,
    'http://aksw.org/schema/hookline', array('tag' => 'p', 'class' => 'hookline'));
?>
<?php echo $this->literalTag($this->description,
    'http://aksw.org/schema/abstract', array('tag' => 'p', 'class' => 'abstract'));
?>
</header> <!-- /.intro -->
<?php echo $this->literalTag($this->description,
    'http://aksw.org/schema/content', array('tag' => 'div', 'class' => 'content'));
?>
