<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org group template
 *
 * arranges the content for the group class
 */

// prepare hookline and abstract (both optional)
// yes, hookline also for groups please :-)
$hookline = $this->literal(array(
    'property' => 'aksw:hookline',
    'class' => 'hookline',
    'prefix' => '<span class="hideme">:</span> '
));
$abstract = $this->literal(array(
    'property' => 'dcterms:abstract',
    'tag' => 'p',
    'class' => 'abstract'
));
$subgroups = $this->query(array(
    'where' => '?resourceUri aiiso:part_of groups:AKSW. ',
    'template' => 'liplain'
));
?>

<header class="intro">
    <h1><?php echo $this->title . $hookline ?></h1>
    <?php echo $abstract ?>
</header> <!-- /.intro -->

<nav class="nav-sidelinks">
<ul>
<li><strong class="headline">sub groups</strong>
<?php echo $subgroups; ?>
</li>
</ul>
</nav>

<?php
echo $this->literal(array('tag' => 'div', 'class' => 'content')); // uses default content properties
?>
<div class="subcolumns">
<?php
    // research areas
    echo $this->query(array(
        'where' => '<'.$this->resourceUri.'> aksw:researchAreas ?resourceUri.',
        'template' => 'liplain',
        'prefix' => '<div class="c60l"><div class="subc"><h1>Research Areas</h1>',
        'suffix' => '</div></div>'
    ));
    // members
    echo $this->query(array(
        'where' => '<'.$this->resourceUri.'> foaf:member ?resourceUri.',
        'template' => 'liplain',
        'prefix' => '<div class="c35r"><div class="subc"><h1>Members</h1>',
        'suffix' => '</div></div>'
    ));
?>
</div>

<?php
    // projects
    echo $this->query(array(
        'where' => '<'.$this->resourceUri.'> foaf:member ?person . ?person foaf:currentProject ?resourceUri.',
        'template' => 'li',
        'prefix' => '<h1>Members</h1>'
    ));
?>
<?php
    // publications
    $publicationTag = $this->literal(array('property' => 'aksw:publicationTag'));
    if ($publicationTag != "") :
?>
<h1>Publications</h1>
<div class="exhibit-filter-tools">
    <!-- use this for lists cantaining a lot of publication and authors-->
    <h2 class="hideme">Filters</h2>
    <div ex:role="facet" ex:facetClass="TextSearch" ex:facetLabel="Keyword"></div>
    <div class="subcolumns equalize">
        <div class="c20l"><div class="subcl">
            <div ex:role="facet" ex:showMissing="false" ex:expression=".year" ex:facetLabel="Year" ex:sortDirection="reverse" ex:height="15em"></div>
        </div></div>
        <div class="c25l"><div class="subc">
            <div ex:role="facet" ex:showMissing="false" ex:expression=".event" ex:facetLabel="Event" ex:sortMode="count" ex:height="15em"></div>
        </div></div>
        <div class="c33r"><div class="subcr">
            <div ex:role="facet" ex:showMissing="false" ex:expression=".author" ex:facetLabel="(Co-)Authors" ex:sortMode="count" ex:height="15em"></div>
        </div></div>
    </div>
</div> <!-- /.exhibit-filter-tools -->

<nav class="nav-sidelinks">
    <div class="exhibit-filter-tools">
        <!-- use this for lists containing only a few publications and authors -->
        <!--div ex:facetClass="Cloud" ex:role="facet" ex:showMissing="false" ex:expression=".year" ex:facetLabel="Year" ex:sortDirection="reverse"></div-->
        <div ex:facetClass="Cloud" ex:role="facet" ex:showMissing="false" ex:expression=".language" ex:facetLabel="Language" ex:sortMode="count"></div>
        <div ex:facetClass="Cloud" ex:role="facet" ex:showMissing="false" ex:expression=".pub-type" ex:facetLabel="Type" ex:sortMode="count"></div>
        <!--div ex:facetClass="Cloud" ex:role="facet" ex:showMissing="false" ex:expression=".author" ex:facetLabel="(Co-)Authors" ex:sortMode="count"></div-->
    </div>
</nav>

<div ex:role="view" ex:grouped="false" ex:orders=".year,.label" ex:directions="descending,ascending" ex:showSummary="true" ex:showDuplicates="false" ex:abbreviatedCount="10">
    <div ex:role="lens" ex:itemTypes="Publication" style="display: none">
        <strong>
            <span ex:content="if(exists(.url), concat('<a href=', .url, '>', .label, '</a>'), .label)"></span>
            <span ex:if-exists=".author">
                <span class="meta"><em>by</em> <span class="author" ex:content=".author"></span></span>
            </span>
        </strong>
        <span class="meta">
            <span ex:content="if(exists(.booktitle), concat('<em>in</em> ', .booktitle), '')"></span>
            <span class="journal" ex:content="if(exists(.journal), concat('<em>in</em> ', .journal), '')"></span>
            <span ex:if-exists=".editor">(Editors: <span class="editor" ex:content=".editor"></span>)</span>
            <a ex:if-exists=".biburl" ex:href-content=".biburl" >[BibTex<span class="hideme"> of <span ex:content=".label"></span></span>]</a>
        </span>
        <span class="note" ex:content="if(exists(.note), concat('<br/><em>Note:</em> ', .note), '')"></span>
        <span class="abstract" ex:content="if(exists(.abstract), concat('<br/><details><summary>Abstract:</summary> ', .abstract, '</details>'), '')"></span>
    </div>
</div>
<?php endif; ?>
