<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org (foaf:)Person template
 *
 * this template renders a person
 */

$subgroups = $this->query(array(
    'where' => '?resourceUri a foaf:Group.',
    'template' => 'liplain',
    'prefix'   => '<li><strong class="headline">sub groups</strong>',
    'suffix'   => '</li>'
));
$grouproster = $this->query(array(
    'where'    => '?group foaf:member <'.$this->resourceUri.'>. ?group foaf:member ?resourceUri.',
    'template' => 'liplain',
    'prefix'   => '<li><strong class="headline">group roster</strong>',
    'suffix'   => '</li>'
));

?>
<header class="intro foaf_Person">
    <h1 class="hideme"><?php echo $this->title ?></h1>
    <?php echo $this->renderx(array('template'=>'aksw2011/items/vcardperson.phtml')) ?>
</header> <!-- /.intro -->

<nav class="nav-sidelinks">
<ul>
<?php echo $grouproster; ?>
<?php echo $subgroups; ?>
</ul>
</nav>

<?php echo $this->literal(array('tag' => 'div', 'class' => 'content')) ?>

<?php // Current Projects
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
    <'.$this->resourceUri.'> foaf:currentProject ?resourceUri.
}
';
if ($currentProjects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
<h1>Current Projects</h1>
<?php echo $currentProjects ?>
<?php endif; ?>
<?php // Past Projects
$query = '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?resourceUri
WHERE {
    <'.$this->resourceUri.'> foaf:pastProject ?resourceUri.
}
';
if ($pastProjects = $this->querylist($query, 'aksw2011/items/li.phtml')): ?>
<h1>Past Projects</h1>
<?php echo $pastProjects ?>
<?php endif; ?>

<?php echo $this->renderx(array(
    'template' => 'aksw2011/items/publications.phtml'
));

