<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * querylist wheel list template
 *
 * this template is used in combination with the querylist helper to render
 * javascript wheels of resources which match a given SPARQL query
 */

// prepare vars from the querylist helper
$resourceUri = $this->resourceUri;
$title       = $this->title;
$oddclass    = $this->oddclass;
$tag         = (isset($this->tag)) ? $this->tag : 'ul';

if ( ($this->listhint == 'first') || ($this->rowcount == 1) ) {
    echo '<div class="demowheel">' . "<$tag>" . PHP_EOL;
}

// if we have a literal item, do not do anything but an li item
if (!Erfurt_Uri::check($resourceUri)) {
    echo "<li class='$oddclass'>$title</li>";
} else {
    // prepare the optional hookline
    $hookline = $this->literal(array(
        'uri'      => $resourceUri,
        'property' => 'aksw:hookline',
        'tag'      => 'span',
        'class'    => 'hookline')
    );
    // prepare the main link
    $link = $this->link(array(
        'uri'    => $resourceUri, 
        'text'   => $title,
        'class'  => '',
        'suffix' => ' ',
        'direct' => 'true'
    ));
    // prepare the screenshot link
    $screenshot    = $this->img(array(
        'property' => 'ov:screenshot',
        'alt'      => 'screenshot',
        'filter'   => 'Resize-width-250'
    ));
    if ($screenshot != '') {
        $shotlink = $this->link(array(
            'uri'    => $resourceUri,
            'text'   => $screenshot,
            'class'  => 'demowheel-image',
            'direct' => 'true',
            'prefix' => '<!-- demo screenshot start -->',
            'suffix' => '<!-- demo screenshot end -->',
        ));
    } else {
        $shotlink = '';
    }
?>
    <li class="<?php echo $oddclass ?>" about="<?php echo $this->curie($resourceUri) ?>">
        <h2 class="demowheel-title"><?php echo $link , $hookline ?></h2>
        <?php echo $shotlink ?>
    </li>
<?php
}

if ( ($this->listhint == 'last') || ($this->rowcount == 1) ) {
    echo "</$tag></div>" . PHP_EOL;
}

/* example markup for demos

<div class="demowheel">
    <ul>
        <li>
            <h3 class="demowheel-title"> <!-- only .demowheel-title is important, you can also use h2/h4/strong/... here -->
                <a class="lightbox" href="#demo-projektinfo1" title="Popup Description">
                    Projekt Demo Name:
                </a>
                Hookline Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </h3>
            <a class="demowheel-image lightbox" href="#demo-projektinfo1" title="Popup Description"> <!-- if there is no link, use span.demoweel-image here -->
                <img src="http://wiki.dbpedia.org/images/dbpedia_logo.png" alt="Demoname Screenshot/Logo/..." />
            </a>
            <div class="demowheel-description" id="demo-projektinfo1">
                <p property="dcterms:abstract" class="abstract">OntoWiki facilitates the visual presentation of a knowledge base as an information map, with different views on instance data. It enables intuitive authoring of semantic content, with an inline editing mode for editing RDF content, similar to WYSIWIG for text documents.</p>
                <p class="button-row">
                    <a href="http://code.google.com/p/ontowiki/source/list" class="button">Fork me!</a>
                    <a href="http://code.google.com/p/ontowiki/downloads/list" class="button">Download</a>
                    <a href="http://ontowiki.net" class="button">Homepage</a>
                </p>
            </div>
        </li>

        <li>
            <h3 class="demowheel-title">
                <a class="lightbox" href="http://linkedgeodata.org/">
                    LinkedGeoData.org:
                </a>
                adding the spatial dimension to the Semantic Web
            </h3>
            <a class="demowheel-image" href="http://linkedgeodata.org/">
                <img src="http://linkedgeodata.org/files/lgdlogo.png" alt="Demoname Screenshot/Logo/..." />
            </a>
        </li>

        <li>
            <h3 class="demowheel-title"> <!-- only .demowheel-title is important, you can also use h2/h4/strong/... here -->
                <a class="lightbox iframe" href="http://player.vimeo.com/video/30014844?portrait=0" title="Popup Description">
                    DBpedia Relationship Finder:
                </a>
                Allows you to explore the DBpedia dataset to find relationships between two things 
            </h3>
            <a class="demowheel-image lightbox iframe" href="http://player.vimeo.com/video/30014844?portrait=0" title="Popup Description"> <!-- if there is no link, use span.demoweel-image here -->
                <img src="http://wiki.aksw.org/images/RelFinder.png" alt="Demoname Screenshot/Logo/..." />
            </a>
        </li>

        <li class="first">
            <h3 class="demowheel-title">
                <a class="lightbox" href="http://wikipedia.aksw.org/">
                    Wikipedia Query Builder:
                </a>
                Query the over 10M facts extracted from Wikipedia 
            </h3>
            <a class="demowheel-image" href="http://wikipedia.aksw.org/">
                <img src="http://wiki.aksw.org/images/wikipedia.png" alt="Demoname Screenshot/Logo/..." />
            </a>
        </li>

        <li>
            <h3 class="demowheel-title"> <!-- only .demowheel-title is important, you can also use h2/h4/strong/... here -->
                <a class="lightbox" href="#demo-projektinfo5" title="Popup Description">
                    Projekt Demo Name:
                </a>
                Hookline Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </h3>
            <a class="demowheel-image lightbox" href="#demo-projektinfo5" title="Popup Description"> <!-- if there is no link, use span.demoweel-image here -->
                <img src="http://wiki.dbpedia.org/images/dbpedia_logo.png" alt="Demoname Screenshot/Logo/..." />
            </a>
            <div class="demowheel-description" id="demo-projektinfo5">
                <p property="dcterms:abstract" class="abstract">OntoWiki facilitates the visual presentation of a knowledge base as an information map, with different views on instance data. It enables intuitive authoring of semantic content, with an inline editing mode for editing RDF content, similar to WYSIWIG for text documents.</p>
                <p class="button-row">
                    <a href="http://code.google.com/p/ontowiki/source/list" class="button">Fork me!</a>
                    <a href="http://code.google.com/p/ontowiki/downloads/list" class="button">Download</a>
                    <a href="http://ontowiki.net" class="button">Homepage</a>
                </p>
            </div>
        </li>

        <li>
            <h3 class="demowheel-title">
                <a class="lightbox" href="http://linkedgeodata.org/">
                    LinkedGeoData.org:
                </a>
                adding the spatial dimension to the Semantic Web
            </h3>
            <a class="demowheel-image" href="http://linkedgeodata.org/">
                <img src="http://linkedgeodata.org/files/lgdlogo.png" alt="Demoname Screenshot/Logo/..." />
            </a>
        </li>

        <li class="first">
            <h3 class="demowheel-title"> <!-- only .demowheel-title is important, you can also use h2/h4/strong/... here -->
                <a class="lightbox iframe" href="http://player.vimeo.com/video/30014844?portrait=0" title="Popup Description">
                    DBpedia Relationship Finder:
                </a>
                Allows you to explore the DBpedia dataset to find relationships between two things 
            </h3>
            <a class="demowheel-image lightbox iframe" href="http://player.vimeo.com/video/30014844?portrait=0" title="Popup Description"> <!-- if there is no link, use span.demoweel-image here -->
                <img src="http://wiki.aksw.org/images/RelFinder.png" alt="Demoname Screenshot/Logo/..." />
            </a>
        </li>

        <li>
            <h3 class="demowheel-title">
                <a class="lightbox" href="http://wikipedia.aksw.org/">
                    Wikipedia Query Builder:
                </a>
                Query the over 10M facts extracted from Wikipedia 
            </h3>
            <a class="demowheel-image" href="http://wikipedia.aksw.org/">
                <img src="http://wiki.aksw.org/images/wikipedia.png" alt="Demoname Screenshot/Logo/..." />
            </a>
        </li>

    </ul>
</div>
 */
